name: Master CICD Pipeline

on:
  push:
    branches: main

jobs:

  build:
    name: Continuous Integration of the endpoint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: |
        git_hash=$(git rev-parse --short HEAD)
        docker build . -t docker.pkg.github.com/<your_username>/<your_repository>/project-api:$git_hash

    - name: Test the Docker image
      run: |
        git_hash=$(git rev-parse --short HEAD)
        docker run \
        --entrypoint=/bin/bash \
        docker.pkg.github.com/<your_username>/<your_repository>/project-api:$git_hash \
        ./script/test
    - name: Login and push the Docker image to Github Packages
      run: |
        git_hash=$(git rev-parse --short HEAD)
        docker login https://docker.pkg.github.com --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
        docker push docker.pkg.github.com/<your_username>/<your_repository>/project-api:$git_hash